name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
    - run: go build ./...
    - run: go test ./...
    - id: generate
      run: |
        go generate
        git diff --exit-code
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - uses: golangci/golangci-lint-action@38e1018663fa5173f3968ea0777460d3de38f256
      with:
        version: v1.58.0
